# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
gems:
  - jekyll-assets
  - jekyll-assets/compass
  - font-awesome-sass

excerpt_separator: <!--more-->

# Permalinks
permalink: /:year/:month/:day/:title/
paginate: 10

# Setup
title:            VR Animation Editor
description:      A tool for Unity for developing better animations in VR
url:              'http://example.org' # The url of your site, without subpath to the blog
baseurl:          'site/' # the subpath of your site, e.g. '/blog'
                                          # or '' for a root github blog
                                          # Note: without leading /


# Author details
email:            muletmiles@ufl.edu
name:             Miles Mulet # For the copyright notice


# Social - you should change these entries for the social sites you want
# to share and remove the ones you don't need
github: muletmiles           # Your github username
#twitter: rcrmn_         # Twitter username
#stackoverflow: 672151   # Stackoverflow user id
#linkedin: rocramon      # linkedin short url name


# Navigation
navigation:
- text: Home
  url: /VRAnimationEditor/
- text: Archive
  url : /VRAnimationEditor/archives
- text: About
  url: /VRAnimationEditor/about
#- text: Portfolio
#  url: http://rcrmn.nl/portfolio


# Disqus
disqushandler: ''
